### ISSUE TITLE
Incompatible with Python 3

### ISSUE THREAD

**Issue by JamesTheAwesomeDude** [jinglemansweep/lcdproc#7]
The program does not work on Python 3.

    Python 3.4.0 (default, Apr 11 2014, 13:05:11) 
    [GCC 4.8.2] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> from lcdproc.server import Server
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/local/lib/python3.4/dist-packages/lcdproc/server.py", line 46
        if self.debug: print "Telnet Request:  %s" % (command_string)
                                                 ^
    SyntaxError: invalid syntax
    >>>

**Comment by emteejay** [comment]
The print statement syntax changed from Python 2 to 3 try the utility script 2to3

**Comment by adicarlo** [comment]
#10 contains a python3 compatibility fix.  I had to fix both the print statement (using `__future__`) and also deal with `urllib` compatibility issues.
